<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MBtecZfLog\Module'                     => __DIR__ . '/Module.php',
    'MBtecZfLog\Formatter\File'             => __DIR__ . '/src/Log/Formatter/File.php',
    'MBtecZfLog\Formatter\Gelf'             => __DIR__ . '/src/Log/Formatter/Gelf.php',
    'MBtecZfLog\Service\StaticLogger'       => __DIR__ . '/src/Log/Service/StaticLogger.php',
    'MBtecZfLog\Service\LogService'         => __DIR__ . '/src/Log/Service/LogService.php',
    'MBtecZfLog\Writer\Graylog2'            => __DIR__ . '/src/Log/Writer/Graylog2.php',
    'MBtecZfLog\Service\LogServiceFactory'  => __DIR__ . '/src/Log/Service/LogServiceFactory.php',
);
