<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MBtec\Log\Module'               => __DIR__ . '/Module.php',
    'MBtec\Log\Formatter\File'       => __DIR__ . '/src/Log/Formatter/File.php',
    'MBtec\Log\Formatter\Gelf'       => __DIR__ . '/src/Log/Formatter/Gelf.php',
    'MBtec\Log\Service\StaticLogger' => __DIR__ . '/src/Log/Service/StaticLogger.php',
    'MBtec\Log\Service\LogService'   => __DIR__ . '/src/Log/Service/LogService.php',
    'MBtec\Log\Writer\Graylog2'      => __DIR__ . '/src/Log/Writer/Graylog2.php',
);
